name: spells_and_tools_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core:
  cloud_firestore: 
  firebase_auth:
  firebase_ui_firestore: 
  firebase_ui_auth: 
  file_picker: ^6.1.1
  

  # State management
  riverpod: 
  flutter_riverpod: 

  # navigation
  go_router:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
