// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHdzujE9hoUyqkXktatxSmm-zQzUQIMMs',
    appId: '1:475193088114:android:f8fc1eb52ff55f535d4aeb',
    messagingSenderId: '475193088114',
    projectId: 'spell-and-tools-dev',
    storageBucket: 'spell-and-tools-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzUBTp3fXZiYMLwlzjlpsvZe3xwto1QjA',
    appId: '1:475193088114:ios:53b7b5faab8db9f95d4aeb',
    messagingSenderId: '475193088114',
    projectId: 'spell-and-tools-dev',
    storageBucket: 'spell-and-tools-dev.firebasestorage.app',
    androidClientId: '475193088114-btp421nq65s13r7sit3ih3d8p2qks8dm.apps.googleusercontent.com',
    iosClientId: '475193088114-tv33s3jpgbtqc1u90os0lbdkbv4d0jd1.apps.googleusercontent.com',
    iosBundleId: 'dev.golski.spellsandtools.dev',
  );

}