// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoVoDFEURzqpUsg_RsnzhWGejj2n3lC6w',
    appId: '1:277623677619:android:f2acfa844a088c68f0c6c6',
    messagingSenderId: '277623677619',
    projectId: 'just-a-rock-dev',
    storageBucket: 'just-a-rock-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFJZ3z7dmUr5Lsn6fW5nozBWOcD9HnMY',
    appId: '1:277623677619:ios:ec9eb5e48a6a5a96f0c6c6',
    messagingSenderId: '277623677619',
    projectId: 'just-a-rock-dev',
    storageBucket: 'just-a-rock-dev.firebasestorage.app',
    androidClientId: '277623677619-0b0javvpumal1p1gnjb8mqq4uuau7vmm.apps.googleusercontent.com',
    iosClientId: '277623677619-a2r32o8pgtrldfdhchp4sb4sft2b5kd5.apps.googleusercontent.com',
    iosBundleId: 'dev.golski.spellsandtools',
  );

}