// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJ0hpcVPAxWB81yJKwk7Ramwey5B-z4o',
    appId: '1:80300784191:web:604ee974c5e474c2de168a',
    messagingSenderId: '80300784191',
    projectId: 'char-creator-dev',
    authDomain: 'char-creator-dev.firebaseapp.com',
    storageBucket: 'char-creator-dev.firebasestorage.app',
    measurementId: 'G-ZFN9PY6VJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpBXBYaOpZO80NciH1FnWIPNqNUPAhkcM',
    appId: '1:80300784191:android:69a16b544818618fde168a',
    messagingSenderId: '80300784191',
    projectId: 'char-creator-dev',
    storageBucket: 'char-creator-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDqRouu6E27hpLW9ln0kCjSuopUWzLaM',
    appId: '1:80300784191:ios:483a3a3669af7b14de168a',
    messagingSenderId: '80300784191',
    projectId: 'char-creator-dev',
    storageBucket: 'char-creator-dev.firebasestorage.app',
    iosBundleId: 'com.example.charCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWDqRouu6E27hpLW9ln0kCjSuopUWzLaM',
    appId: '1:80300784191:ios:483a3a3669af7b14de168a',
    messagingSenderId: '80300784191',
    projectId: 'char-creator-dev',
    storageBucket: 'char-creator-dev.firebasestorage.app',
    iosBundleId: 'com.example.charCreator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvJ0hpcVPAxWB81yJKwk7Ramwey5B-z4o',
    appId: '1:80300784191:web:d10ccd46414a86f4de168a',
    messagingSenderId: '80300784191',
    projectId: 'char-creator-dev',
    authDomain: 'char-creator-dev.firebaseapp.com',
    storageBucket: 'char-creator-dev.firebasestorage.app',
    measurementId: 'G-9SPM7Q0Y0J',
  );
}
